baseURL = "https://blabel.dev/"
languageCode = "en-us"
title = "Blabel"

[params]
    author = "Blake Abel"
    description = "Blake Abel (Blabel!)'s online home base."
    
    stylesheet = "styles.css"
    #script = "app.js" (No script currently in the site)
    analytics = true
